

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.moviestorage.moviestorage.vo

logging:
  level:
    com:
      moviestorage: debug

